# Generated by Django 4.0.1 on 2022-01-26 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_teacher_course_pass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=10, unique=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_password',
            field=models.IntegerField(verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.IntegerField(choices=[(1, '管理员'), (2, '教师'), (3, '学生')], default=3, verbose_name='用户类型'),
        ),
    ]
