# Generated by Django 4.0.1 on 2022-01-26 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_user_user_name_alter_user_user_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='text',
        ),
        migrations.AddField(
            model_name='question',
            name='its_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher', to_field='the_course'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
    ]
