# Generated by Django 4.0.1 on 2022-01-26 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_question_text_question_its_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='its_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher', to_field='the_course'),
        ),
    ]
