# Generated by Django 4.0.1 on 2022-01-30 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_student_course_alter_student_student_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='成绩'),
        ),
        migrations.AddField(
            model_name='student',
            name='teacher_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='t_name', to='myapp.user', to_field='user_name', verbose_name='老师名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='student_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_name', to='myapp.user', to_field='user_name', verbose_name='学生名'),
        ),
    ]
