# Generated by Django 4.0.1 on 2022-02-04 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_student_grade_student_teacher_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='ChoiceQuestion',
        ),
        migrations.CreateModel(
            name='TFQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='问题')),
                ('answer', models.BooleanField(verbose_name='正确答案')),
                ('its_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher', to_field='the_course', verbose_name='所属课程')),
            ],
        ),
        migrations.CreateModel(
            name='Completion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='问题')),
                ('answer', models.CharField(max_length=20, verbose_name='正确答案')),
                ('its_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher', to_field='the_course', verbose_name='所属课程')),
            ],
        ),
    ]
