# Generated by Django 4.0.1 on 2022-02-17 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_question_choicequestion_tfquestion_completion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200, verbose_name='问题')),
                ('answer', models.CharField(max_length=20, verbose_name='正确答案')),
                ('stu_anw', models.CharField(max_length=20, verbose_name='学生答案')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.teacher', to_field='the_course', verbose_name='课程名')),
                ('student_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stu_name', to='myapp.user', to_field='user_name', verbose_name='学生名')),
            ],
        ),
    ]
