# Generated by Django 4.0.1 on 2022-02-17 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_anw_tof'),
    ]

    operations = [
        migrations.AddField(
            model_name='anw',
            name='type_of_questions',
            field=models.CharField(default=1, max_length=20, verbose_name='题目类型'),
            preserve_default=False,
        ),
    ]
